# Template attrs
DRAWING_TEMPLATE_NAME = "name"
DRAWING_TEMPLATE_WIDTH = "width"
DRAWING_TEMPLATE_HEIGHT = "height"
DRAWING_TEMPLATE_RECT_WIDTH = "rect_width"
DRAWING_TEMPLATE_RECT_HEIGHT = "rect_height"
DRAWING_TEMPLATE_RECT_TOP = "rect_top"
DRAWING_TEMPLATE_RECT_LEFT = "rect_left"
DRAWING_TEMPLATE_RECT_RIGHT = "rect_right"
DRAWING_TEMPLATE_RECT_BOTTOM = "rect_bottom"
DRAWING_TEMPLATE_RECT_DIP_START = "rect_dip_start"
DRAWING_TEMPLATE_RECT_DIP_INSERT = "dip_insert"
DRAWING_TEMPLATE_RECT_TITLE_INSERT = "title_insert"
DRAWING_TEMPLATE_PIN_LENGTH = "pin_length"
DRAWING_TEMPLATE_TITLE_TEXT_SIZE = "title_text_size"
DRAWING_TEMPLATE_PIN_TEXT_SIZE = "pin_text_size"
DRAWING_TEMPLATE_CONNECTION_INSERT = "connection_insert"
DRAWING_TEMPLATE_PINS_INSERT = "pins_insert"

DIP_TEMPLATE_END_X = "end_x"
DIP_TEMPLATE_END_Y = "end_y"
DIP_TEMPLATE_RADIUS = "radius"

CONNECTION_TEMPLATE_NAME = "name"
CONNECTION_TEMPLATE_X = "x"
CONNECTION_TEMPLATE_Y = "y"

TITLE_TEMPLATE_TITLE = "title"
TITLE_TEMPLATE_X = "x"
TITLE_TEMPLATE_Y = "y"

LEAD_TEMPLATE_X_START = "x_start"
LEAD_TEMPLATE_Y_START = "y_start"
LEAD_TEMPLATE_X_END = "x_end"
LEAD_TEMPLATE_Y_END = "y_end"

PIN_TEMPLATE_X = "x"
PIN_TEMPLATE_Y = "y"
PIN_TEMPLATE_NAME = "name"
PIN_TEMPLATE_TEXT_ALIGN = "align"
PIN_TEMPLATE_TEXT_VALIGN = "valign"

ARROW_TEMPLATE_TOP = "top"
ARROW_TEMPLATE_BOTTOM = "bottom"
ARROW_TEMPLATE_MIDDLE = "middle"
ARROW_TEMPLATE_X_POINT = "x_point"
ARROW_TEMPLATE_X_FLAT = "x_flat"

# Template locations
TEMPLATE_MAIN = "templates/template.xml"
TEMPLATE_TITLE = "templates/template_title.xml"
TEMPLATE_LEAD = "templates/template_lead.xml"
TEMPLATE_PIN_HORIZ = "templates/template_pin_horiz.xml"
TEMPLATE_PIN_VERT = "templates/template_pin_vert.xml"
TEMPLATE_CONNECTION = "templates/template_connection.xml"
TEMPLATE_DIP = "templates/template_dip.xml"
TEMPLATE_NO_DIP = "templates/template_no_dip.xml"
TEMPLATE_DIP = "templates/template_dip.xml"
TEMPLATE_ARROW = "templates/template_arrow.xml"


# Src and dist dirs
YAML_SRC_DIR = "drawings"
YAML_STYLE_DIR = "styles"
YAML_DIST_DIR = "dist"

# Drawing YAML names
DRAWING_YAML_SCHEMA_VERSION = "schema_version"
DRAWING_YAML_DISABLE = "disable"
DRAWING_YAML_DIP = "dip"
DRAWING_YAML_BLOCK = "block"
DRAWING_YAML_STYLE = "style"
DRAWING_YAML_TITLE = "title"
DRAWING_YAML_LEFT = "left"
DRAWING_YAML_TOP = "top"
DRAWING_YAML_RIGHT = "right"
DRAWING_YAML_BOTTOM = "bottom"

# Style YAML names
STYLE_YAML_BASE = "base"
STYLE_YAML_BASE_WIDTH = "width"
STYLE_YAML_BASE_HEIGHT = "height"
STYLE_YAML_TITLE_TEXT = "title_text"
STYLE_YAML_TITLE_TEXT_SIZE = "size"
STYLE_YAML_TITLE_TEXT_LINE_SPACING = "line_spacing"
STYLE_YAML_PIN_TEXT = "pin_text"
STYLE_YAML_PIN_TEXT_VERT_WIDTH = "vert_width"
STYLE_YAML_PIN_TEXT_HORIZ_HEIGHT = "horiz_height"
STYLE_YAML_PIN_TEXT_SIZE = "size"
STYLE_YAML_PIN_TEXT_LINE_SPACING = "line_spacing"
STYLE_YAML_PIN_TEXT_PAD = "pad"
STYLE_YAML_PINS = "pins"
STYLE_YAML_PINS_LENGTH = "length"
STYLE_YAML_PINS_ARROW_SIZE = "arrow_size"
STYLE_YAML_PINS_LEFT_ARROW_PAD = "left_arrow_pad"

# Template attr values
TEXT_ALIGN_LEFT = "left"
TEXT_ALIGN_RIGHT = "right"
TEXT_ALIGN_CENTER = "center"
TEXT_VALIGN_TOP = "top"
TEXT_VALIGN_BOTTOM = "bottom"
TEXT_VALIGN_MIDDLE = "middle"
